/**
*
*	@file		temperature_reader.hpp
*
*	@brief		Public API for the temperature_reader module
*
*	@details	Adapter module for Zephyr's Sensor API
*
*				Supports temperature reading and Zephyr's Sensor API return values
*
*/

#ifndef TEMPERATURE_READER_HPP
#define TEMPERATURE_READER_HPP

#include "temperature_reader_interface.hpp"
#include <cstddef>
#include <zephyr/device.h>
#include <zephyr/rtio/rtio.h>
#include <zephyr/drivers/sensor.h>
#include <zephyr/drivers/sensor_data_types.h>

#define CONCAT_UNDRSCR(str1, str2) str1 ## _ ## str2
#define DEFINE_TEMPERATURE_SENSOR(alias) SENSOR_DT_READ_IODEV(CONCAT_UNDRSCR(iodev, alias), DT_ALIAS(alias), {SENSOR_CHAN_AMBIENT_TEMP, 0}); \
		\
		RTIO_DEFINE(CONCAT_UNDRSCR(ctx, alias), 1, 1); \
		\
		temperature_reader::SensorDevice CONCAT_UNDRSCR(alias, device){ \
			{DEVICE_DT_GET(DT_ALIAS(alias))}, \
			{&CONCAT_UNDRSCR(iodev, alias)}, \
			{&CONCAT_UNDRSCR(ctx, alias)} \
		};

#define TEMPERATURE_SENSOR_DEVICE(alias) CONCAT_UNDRSCR(alias, device)

namespace temperature_reader {

	struct SensorDevice {
		const struct device* const device_ptr = nullptr;
		const struct rtio_iodev* const iodev_ptr = nullptr;
		struct rtio* const ctx_ptr = nullptr;
	};

	class TemperatureSignal : public temperature_reader_interface::TemperatureSignalInterface {

		public:

			explicit TemperatureSignal(temperature_reader::SensorDevice temperature_sensor_device);

			/*
			*
			*	Copy/move constructors/operators are deleted to prevent the creation of a copy of this class through these operations
			*
			*/
			TemperatureSignal(const TemperatureSignal&) = delete;
			TemperatureSignal(TemperatureSignal&&) = delete;
			TemperatureSignal& operator=(const TemperatureSignal&) = delete;
			TemperatureSignal& operator=(TemperatureSignal&&) = delete;

			temperature_reader_interface::ErrorCode single_read(int& temp_c_x100) override;

			void value_get(int& temp_c_x100) const override;
			[[nodiscard("Called error getter and discarded its return value")]]
			temperature_reader_interface::ErrorState error_state_get() const override;

		private:

			struct SensorState {
				const struct device* const device_ptr;
				const struct rtio_iodev* const iodev_ptr;
				struct rtio* const ctx_ptr;
				const struct sensor_decoder_api* const decoder = {};
			};

			struct SystemState {
				bool sensor_acquired = false;
			};

			struct ReadingState {
				struct sensor_q31_data internal_data = {};
				int temp_c_x100 = 0;
			};

			temperature_reader_interface::ErrorState error;
			temperature_reader::TemperatureSignal::SystemState system;
			temperature_reader::TemperatureSignal::SensorState sensor;
			temperature_reader::TemperatureSignal::ReadingState reading;

			[[nodiscard("Internal error: necessary struct discarded")]]
			const struct sensor_decoder_api* const init_operations(const struct device* const temperature_sensor_device_ptr);
	};
}

#endif

/**
*
*	@enum		temperature_reader_interface::ErrorCode
*
*	@brief		Error codes of the module
*
*	@invariant	If an error related to Zephyr's Sensor API occurs then the code is prefixed with "ZSensor"
*
*/

/**
*
*	@struct		temperature_reader_interface::ErrorState
*
*	@brief		Data structure for all types of errors
*
*	@invariant	All members of this struct are set at the end of every fallible method of TemperatureSignal
*	@invariant	If a module-based error occurs then it is represented by code and the other member is equal to 0
*	@invariant	If an error related to Zephyr's Sensor API occurs then it is represented by both code and return_value
*
*/

/**
*
*	@struct		temperature_reader::SensorDevice
*
*	@brief		Device-related spec struct used by the constructor and passed by the caller
*
*	@note		The caller should obtain a valid instance of this struct by using the provided macro "DEFINE_TEMPERATURE_READER"
*
*/

/**
*
*	@class		temperature_reader::TemperatureSignal
*
*	@brief		Class for Zephyr's Sensor API
*
*	@warning	Since each instance of this class represents a different device there should not exist copies
*
*/

/**
*
*	@fn			temperature_reader::TemperatureSignal::TemperatureSignal(temperature_reader::SensorDevice temperature_reader)
*
*	@brief		Constructor to initialize the sensor
*
*	@param[in]	temperature_reader		SensorDevice struct for the instance
*
*	@pre		temperature_reader is a valid SensorDevice struct generated by using "DEFINE_TEMPERATURE_READER" and passed by using "TEMPERATURE SENSOR DEVICE"
*	@post		If the target sensor is not ready to be used then error.code is set to DeviceUnready
*	@post		If an error occurs when obtaining the decoder with Zephyr's Sensor API then its return value is saved in error.return_value and error.code is set to ZSensorDecoderGet
*	@post		On success the target device is ready, the sensor is initialized and error.code is set to Ok
*
*/

/**
*
*	@fn			temperature_reader_interface::ErrorCode temperature_reader::TemperatureSignal::temp_read(std::int16_t& temp_c_x100);
*
*	@brief		Method to read the temperature from the sensor and expose it in hundredth of Celsius degrees
*
*	@param[out]	temp_c_x100						Reference to the variable where to store the temperature
*
*	@retval		ReadingUnready					If the reading function is not ready to be used
*	@retval		ZSensorRead						If an error occurs when reading the temperature from the sensor
*	@retval		ZSensorDecode					If an error occurs when decoding the reading value
*	@retval		Ok								If no error occurs
*
*	@post		If the reading function is not ready to be used then error.code is set to ReadingUnready
*	@post		If an error occurs when reading the temperature from the sensor with Zephyr's Sensor API then its return value is saved in error.return_value and error.code is set to ZSensorRead
*	@post		If an error occurs when decoding the reading value with Zephyr's Sensor API then its return value is saved in error.return_value and error.code is set to ZSensorDecode
*	@post		On success the temperature is read from the sensor, its value is decoded and assigned to the reference and error.code is set to Ok
*
*/

/**
*
*	@fn			temperature_reader_interface::ErrorState temperature_reader::TemperatureSignal::error_state_get() const
*
*	@brief		Method to obtain the full error report
*
*	@return										The full error struct
*
*/
