/**
*
*	@file		temperature_sensor.hpp
*
*	@brief		Public API for the temperature_sensor module
*
*	@details	Adapter module for Zephyr's Sensor API
*
*				Supports temperature reading and Zephyr's Sensor API return values
*
*/

#ifndef TEMPERATURE_SENSOR_HPP
#define TEMPERATURE_SENSOR_HPP

#include <cstdint>
#include <cstddef>
#include <zephyr/device.h>
#include <zephyr/rtio/rtio.h>
#include <zephyr/drivers/sensor.h>
#include <zephyr/drivers/sensor_data_types.h>

#define CONCAT_UNDRSCR(str1, str2) str1 ## _ ## str2
#define DEFINE_TEMPERATURE_SENSOR(alias) SENSOR_DT_READ_IODEV(CONCAT_UNDRSCR(iodev, alias), DT_ALIAS(alias), {SENSOR_CHAN_AMBIENT_TEMP, 0}); \
		\
		RTIO_DEFINE(CONCAT_UNDRSCR(ctx, alias), 1, 1); \
		\
		temperature_sensor::SensorState CONCAT_UNDRSCR(temperature_sensor, alias){ \
			{DEVICE_DT_GET(DT_ALIAS(alias))}, \
			{&CONCAT_UNDRSCR(iodev, alias)}, \
			{&CONCAT_UNDRSCR(ctx, alias)} \
		};

#define TEMPERATURE_SENSOR_DEVICE(alias) CONCAT_UNDRSCR(temperature_sensor, alias)

namespace temperature_sensor {

	enum class [[nodiscard("Discarding an error of this type may result in a bug")]] ErrorCode {
		Ok,
		DeviceUnready,
		ReadingUnready,
		ZSensorDecoderGet,
		ZSensorRead,
		ZSensorDecode
	};

	struct ErrorState {
		temperature_sensor::ErrorCode code = temperature_sensor::ErrorCode::Ok;
		int return_value = 0;
	};

	struct SensorState {
		const struct device* const device_ptr;
		const struct rtio_iodev* const iodev_ptr;
		struct rtio* const ctx_ptr;
		const struct sensor_decoder_api* const decoder = {};
	};

	class TemperatureSensor {

		public:

			TemperatureSensor(temperature_sensor::SensorState temperature_sensor);

			/*
			*
			*	Copy/move constructors/operators are deleted to prevent the creation of a copy of this class through these operations
			*
			*/
			TemperatureSensor(const TemperatureSensor&) = delete;
			TemperatureSensor(TemperatureSensor&&) = delete;
			TemperatureSensor& operator=(const TemperatureSensor&) = delete;
			TemperatureSensor& operator=(TemperatureSensor&&) = delete;

			temperature_sensor::ErrorCode temp_read(std::int16_t& temp_c_x100);

			[[nodiscard("Called error getter and discarded its return value")]] temperature_sensor::ErrorState error_state_get() const;

		private:

			struct SystemState {
				bool reading_ready = false;
			};

			struct ReadingState {
				struct sensor_q31_data internal_data = {};
				std::int16_t temp_c_x100 = 0;
			};


			temperature_sensor::ErrorState error;
			temperature_sensor::TemperatureSensor::SystemState system;
			temperature_sensor::SensorState sensor;

			temperature_sensor::TemperatureSensor::ReadingState reading;

			[[nodiscard("Internal error: necessary struct discarded")]] const struct sensor_decoder_api* const init_operations(const struct device* const temperature_sensor_ptr);
	};
}

#endif

/**
*
*	@enum		temperature_sensor::ErrorCode
*
*	@brief		Error codes of the module
*
*	@invariant	If an error related to Zephyr's Sensor API occurs then the code is prefixed with "ZSensor"
*
*/

/**
*
*	@struct		temperature_sensor::ErrorState
*
*	@brief		Data structure for all types of errors
*
*	@invariant	All members of this struct are set at the end of every fallible method of TemperatureSensor
*	@invariant	If a module-based error occurs then it is represented by code and the other member is equal to 0
*	@invariant	If an error related to Zephyr's Sensor API occurs then it is represented by both code and return_value
*
*/

/**
*
*	@struct		temperature_sensor::SensorDevice
*
*	@brief		Device-related spec struct used by the constructor and passed by the caller
*
*	@note		The caller should obtain a valid instance of this struct by using the provided macro "DEFINE_TEMPERATURE_SENSOR"
*
*/

/**
*
*	@class		temperature_sensor::TemperatureSensor
*
*	@brief		Class for Zephyr's Sensor API
*
*	@warning	Since each instance of this class represents a different device there should not exist copies
*
*/

/**
*
*	@fn			temperature_sensor::TemperatureSensor::TemperatureSensor(temperature_sensor::SensorDevice temperature_sensor)
*
*	@brief		Constructor to initialize the sensor
*
*	@param[in]	temperature_sensor		SensorDevice struct for the instance
*
*	@pre		temperature_sensor is a valid SensorDevice struct generated by using "DEFINE_TEMPERATURE_SENSOR" and passed by using "TEMPERATURE SENSOR DEVICE"
*	@post		If the target sensor is not ready to be used then error.code is set to DeviceUnready
*	@post		If an error occurs when obtaining the decoder with Zephyr's Sensor API then its return value is saved in error.return_value and error.code is set to ZSensorDecoderGet
*	@post		On success the target device is ready, the sensor is initialized and error.code is set to Ok
*
*/

/**
*
*	@fn			temperature_sensor::ErrorCode temperature_sensor::TemperatureSensor::temp_read(std::int16_t& temp_c_x100);
*
*	@brief		Method to read the temperature from the sensor and expose it in hundredth of Celsius degrees
*
*	@param[out]	temp_c_x100						Reference to the variable where to store the temperature
*
*	@retval		ReadingUnready					If the reading function is not ready to be used
*	@retval		ZSensorRead						If an error occurs when reading the temperature from the sensor
*	@retval		ZSensorDecode					If an error occurs when decoding the reading value
*	@retval		Ok								If no error occurs
*
*	@post		If the reading function is not ready to be used then error.code is set to ReadingUnready
*	@post		If an error occurs when reading the temperature from the sensor with Zephyr's Sensor API then its return value is saved in error.return_value and error.code is set to ZSensorRead
*	@post		If an error occurs when decoding the reading value with Zephyr's Sensor API then its return value is saved in error.return_value and error.code is set to ZSensorDecode
*	@post		On success the temperature is read from the sensor, its value is decoded and assigned to the reference and error.code is set to Ok
*
*/

/**
*
*	@fn			temperature_sensor::ErrorState temperature_sensor::TemperatureSensor::error_state_get() const
*
*	@brief		Method to obtain the full error report
*
*	@return										The full error struct
*
*/
